### ISSUE TITLE
Minecraft-forge1.18消息源兼容问题

### ISSUE THREAD

**Issue by Beyond121** [MeowCat-Studio/mesagisto#67]
Minecraft-forge1.18消息源与模组Kotlin for Forge同时安装时会导致服务器无法启动。

**Comment by Itsusinn** [comment]
有日志吗？

**Comment by Beyond121** [comment]
C:\Users\Administrator\Desktop\server>REM Forge requires a configured set of both JVM and program arguments.

C:\Users\Administrator\Desktop\server>REM Add custom JVM arguments to the user_jvm_args.txt

C:\Users\Administrator\Desktop\server>REM Add custom program arguments {such as nogui} to this file in the next line before the  or

C:\Users\Administrator\Desktop\server>REM  pass them to this script directly

C:\Users\Administrator\Desktop\server>java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.2.0/win_args.txt
2023-01-15 02:31:48,733 main WARN Advanced terminal features are not available in this environment
[02:31:48] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.2.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[02:31:48] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.5 by Oracle Corporation
[02:31:49] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Administrator/Desktop/server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[02:31:49] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[02:31:49] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[02:31:49] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[02:31:49] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar is missing mods.toml file
[02:31:50] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 3 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules mesagisto and thedarkcolour.kotlinforforge export package org.jetbrains.annotations to module forge
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

C:\Users\Administrator\Desktop\server>pause
请按任意键继续. . .

**Comment by Itsusinn** [comment]
mcmod源 1.3.0 已尝试解决该问题，请尝试一下

**Comment by Beyond121** [comment]
还是会这样）
这是日志：

C:\Users\Administrator\Desktop\server>REM Forge requires a configured set of both JVM and program arguments.

C:\Users\Administrator\Desktop\server>REM Add custom JVM arguments to the user_jvm_args.txt

C:\Users\Administrator\Desktop\server>REM Add custom program arguments {such as nogui} to this file in the next line before the  or

C:\Users\Administrator\Desktop\server>REM  pass them to this script directly

C:\Users\Administrator\Desktop\server>java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.2.0/win_args.txt
2023-01-15 18:29:57,487 main WARN Advanced terminal features are not available in this environment
[18:29:57] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.2.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[18:29:57] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.5 by Oracle Corporation
[18:29:58] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Administrator/Desktop/server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[18:29:58] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[18:29:59] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[18:29:59] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[18:29:59] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\server\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar is missing mods.toml file
[18:29:59] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 3 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules mesagisto and thedarkcolour.kotlinforforge export package kotlin.reflect.jvm.internal.impl.load.java to module forge
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

C:\Users\Administrator\Desktop\server>pause
请按任意键继续. . .

**Comment by Itsusinn** [comment]
请尝试 https://github.com/Mesagisto/mcmod-message-source/releases/tag/latest

**Comment by Beyond121** [comment]
依旧不行，测试过单独安装Kotlin for Forge或者Mesagisto都可以正常启动，并且服务器没有安装其他模组

**Comment by Itsusinn** [comment]
怪了我自己试了试可以啊，和kotlin for forge放在一起跑的

**Comment by Itsusinn** [comment]
请再尝试 https://github.com/Mesagisto/mcmod-message-source/releases/tag/latest

**Comment by Beyond121** [comment]
好了，感谢
